/**
 * A library you can actually open.
 *
 * Lectern is hard to understand from a screenshot: the point is a pile of papers,
 * a manuscript that cites them, and Claude Code pointed at the same folder. So
 * ship a small working example of exactly that — `lectern --demo <folder>`, or
 * `npm run example` to regenerate the copy committed under `examples/library`.
 *
 * It is built by calling the SAME functions the app calls (`addLibraryPapers`,
 * `createProject`, `updateLibraryPaper`, …) rather than by committing a
 * hand-written `library.json`. The previous checked-in example rotted precisely
 * because it was hand-written: it still used `.sources/` and `.lectern/` long
 * after the code moved to `sources/` and `.lctrn/`, and its PDFs were zero bytes.
 * Generating it means the example cannot describe a layout the code doesn't
 * produce.
 *
 * The papers are FICTIONAL — synthesised here with pdf-lib rather than shipped
 * as real PDFs, which keeps the repo free of redistribution questions and
 * guarantees a text layer for search and citekey extraction. They are written to
 * look like the accounting/sustainability literature the app was built for. The
 * DOIs are deliberately absent so nothing here invites a Crossref lookup for a
 * paper that does not exist.
 */

import { promises as fs } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import {
  addLibraryPapers,
  addProjectPaper,
  createProject,
  renamePaperToHouseStyle,
  updateLibraryPaper,
  type PaperPatch
} from './library'
import { saveDoc } from './quarto'

interface DemoPaper {
  /**
   * Import filename. Only a starting point — after the metadata below is
   * applied, the file is renamed by the app's own house-style rule, so what
   * lands in `sources/` is whatever the current rule produces.
   */
  file: string
  patch: PaperPatch
  /** Body sections rendered into the PDF, so the text layer is worth searching. */
  sections: { heading: string; paragraphs: string[] }[]
}

const AFFILIATION = 'Fictional example paper — generated by Lectern for demonstration.'

const PAPERS: DemoPaper[] = [
  {
    file: 'Ingram and Okonkwo 2024 JSA, Mandatory carbon disclosure cost of capital.pdf',
    patch: {
      citekey: 'ingram2024',
      title: 'Mandatory Carbon Disclosure and the Cost of Capital',
      authors: ['Ingram, Alice', 'Okonkwo, Ngozi'],
      year: '2024',
      journal: 'Journal of Sustainability Accounting',
      journalAbbrev: 'JSA',
      volume: '12',
      issue: '3',
      pages: '441-478',
      abstract:
        'We exploit a staggered national rollout of mandatory carbon disclosure to estimate its effect on the cost of equity capital. Firms brought into scope report a decline in implied cost of capital of roughly 38 basis points relative to not-yet-treated peers, concentrated among firms with previously sparse voluntary reporting. The effect is larger where an assurance requirement accompanies the mandate, and absent where disclosure is unaudited. We interpret this as evidence that the credibility of the disclosure, not its existence, is what investors price.'
    },
    sections: [
      {
        heading: '1. Introduction',
        paragraphs: [
          'Whether mandatory sustainability disclosure changes the cost of capital is an old question with a thin empirical record. Most settings introduce a mandate everywhere at once, leaving no clean counterfactual. We use a rollout that phased firms in by size threshold over four years, which lets us compare firms brought into scope against firms not yet in scope but subject to the same regime.',
          'Our contribution is twofold. First, we provide a credible causal estimate in a setting with staggered adoption. Second, we show that the effect depends on whether the mandate carries an assurance requirement, which speaks directly to the debate over whether disclosure regulation should specify verification.'
        ]
      },
      {
        heading: '2. Institutional setting',
        paragraphs: [
          'The regime obliges in-scope firms to publish scope 1 and scope 2 emissions in the annual report, with scope 3 required only where material. Phase-in was determined by a headcount threshold measured two years before the reporting year, which firms could not plausibly manipulate at the margin we study.',
          'Assurance was required only for firms above a second, higher threshold. This gives us a within-mandate comparison between assured and unassured disclosers, holding the disclosure requirement itself constant.'
        ]
      },
      {
        heading: '3. Results',
        paragraphs: [
          'Table 3 reports the baseline difference-in-differences estimate. The coefficient on the treatment indicator is -0.38 percentage points with a standard error of 0.11, clustered by firm. Event-study estimates show no differential pre-trend in the three years before phase-in.',
          'Splitting by assurance, the effect for assured disclosers is -0.61 percentage points, while the estimate for unassured disclosers is statistically indistinguishable from zero. We take this as the central result of the paper.'
        ]
      }
    ]
  },
  {
    file: 'Vasquez, Lindqvist, and Osei 2023 A&S, Boilerplate in climate risk reporting.pdf',
    patch: {
      citekey: 'vasquez2023',
      title: 'What Firms Say When They Say Nothing: Boilerplate in Climate Risk Reporting',
      authors: ['Vasquez, Rosa', 'Lindqvist, Mats', 'Osei, Kwame'],
      year: '2023',
      journal: 'Accounting and Society',
      journalAbbrev: 'A&S',
      volume: '48',
      issue: '2',
      pages: '203-241',
      abstract:
        'We measure textual similarity across climate risk disclosures in 6,400 annual reports and document that a large share of reported climate risk is boilerplate: near-identical language recycled across firms and years. Boilerplate intensity rises sharply in the first year a firm is required to disclose and falls only where an activist investor or a regulator has previously challenged the filing. Firms with high boilerplate intensity show no relationship between their stated risks and their subsequent physical loss events.'
    },
    sections: [
      {
        heading: '1. Motivation',
        paragraphs: [
          'Disclosure mandates assume that requiring a firm to describe a risk causes it to reveal something. That assumption fails if firms satisfy the requirement with language that carries no firm-specific content. We ask how much climate risk disclosure is of this kind.',
          'We build a similarity measure over disclosure passages and validate it against hand-coded assessments by two trained readers. Agreement is high for the extremes and weaker in the middle of the distribution, which we discuss as a limitation.'
        ]
      },
      {
        heading: '2. Method',
        paragraphs: [
          'For each report we extract the climate risk section and compute pairwise cosine similarity against every other firm-year in the sample. A passage is classified as boilerplate when its maximum similarity to a passage filed by an unrelated firm exceeds a threshold calibrated on the hand-coded subsample.',
          'We deliberately avoid interpreting the measure as a proxy for disclosure quality. It captures distinctiveness, and a distinctive disclosure can still be uninformative.'
        ]
      },
      {
        heading: '3. Findings and limitations',
        paragraphs: [
          'Roughly 44 per cent of climate risk passages in the first mandated year meet our boilerplate threshold, against 19 per cent by the fourth year. The decline is driven almost entirely by firms that faced external challenge; unchallenged firms show a flat profile.',
          'Our design cannot separate genuine convergence on good practice from coordinated copying. Where several firms share an advisor, similar language may reflect a shared and defensible template rather than evasion.'
        ]
      }
    ]
  },
  {
    file: 'Haugen and Petrov 2025 REA, Measuring assurance quality sustainability reports.pdf',
    patch: {
      citekey: 'haugen2025',
      title: 'Measuring Assurance Quality in Sustainability Reports: A Framework',
      authors: ['Haugen, Sigrid', 'Petrov, Dimitar'],
      year: '2025',
      journal: 'Review of Environmental Accounting',
      journalAbbrev: 'REA',
      volume: '9',
      issue: '1',
      pages: '55-92',
      abstract:
        'Assurance over sustainability reporting is widely required and poorly measured. We propose a framework that separates assurance scope, assurance depth, and assurer competence, and show that the three components move independently across a sample of 2,100 assured reports. Studies that collapse them into a single binary indicator will understate the variation that matters. We provide a coding scheme and report inter-coder reliability.'
    },
    sections: [
      {
        heading: '1. The measurement problem',
        paragraphs: [
          'Most empirical work treats assurance as a binary: the report is assured or it is not. That indicator hides enormous variation. An engagement covering three emissions metrics at limited assurance by a non-accounting provider is coded identically to a reasonable-assurance engagement over the whole report by a Big Four firm.',
          'We argue that this measurement choice, rather than any underlying economic null, explains part of the inconsistency in the literature on whether assurance is valued.'
        ]
      },
      {
        heading: '2. A three-component framework',
        paragraphs: [
          'Scope is the fraction of reported metrics covered by the engagement. Depth distinguishes limited from reasonable assurance. Competence captures whether the assurer holds a relevant accreditation and the share of its practice in sustainability engagements.',
          'Across our sample the pairwise correlations between the three components range from 0.09 to 0.31, which is low enough that a single index would discard most of the information.'
        ]
      },
      {
        heading: '3. Using the framework',
        paragraphs: [
          'We re-estimate three published specifications using the decomposed measures. In each case the binary indicator is insignificant while at least one component is significant, and in one case two components carry opposite signs.',
          'The coding scheme is reproduced in the appendix. Two coders applied it independently to 200 reports with a Krippendorff alpha of 0.81.'
        ]
      }
    ]
  }
]

const MANUSCRIPT = `## Introduction

This is a demonstration manuscript. It is a normal Quarto document
(\`manuscript.qmd\`) that cites the library's shared bibliography, so a citation
like @ingram2024 resolves against \`.lctrn/references.bib\` — the one bib
generated from the whole paper pile, not a per-project copy.

The question this stub sets up: mandatory climate disclosure changes what firms
publish, but does it change what investors learn? @ingram2024 finds a cost of
capital effect that appears only where the disclosure is assured, while
@vasquez2023 shows that a large share of mandated climate risk language is
recycled boilerplate. Read together they suggest that the binding constraint is
credibility rather than volume.

## What to try here

1. **Open a paper.** Double-click a row in Papers. The PDF opens in the reader
   with a notes pane beside it; notes are saved as markdown under \`notes/\`.
2. **Cite one.** Type \`@\` in this editor to pull up citekey completion from the
   library.
3. **Render it.** Render to PDF or HTML — this needs Quarto installed.
4. **Hand it to Claude.** Open the terminal below and ask for something concrete,
   e.g. *"tighten the introduction and make sure every claim cites a paper in the
   bibliography"*. Claude Code runs in this folder and edits the same files you
   are looking at.
5. **Review what changed.** Every turn is snapshotted, so the review panel shows
   what Claude touched, grouped by the prompt that caused it, with keep or revert
   per file.

## Notes

The three papers in this library are fictional, generated to give the demo
something with a real text layer to search. Replace them with your own PDFs —
drop them into \`sources/\` and the watcher will register them.
`

/** Render one demo paper to a PDF with a genuine, searchable text layer. */
async function writePdf(path: string, paper: DemoPaper): Promise<void> {
  const doc = await PDFDocument.create()
  const body = await doc.embedFont(StandardFonts.TimesRoman)
  const bold = await doc.embedFont(StandardFonts.TimesRomanBold)
  const italic = await doc.embedFont(StandardFonts.TimesRomanItalic)

  const W = 595.28 // A4
  const H = 841.89
  const M = 72
  const width = W - M * 2

  let page = doc.addPage([W, H])
  let y = H - M

  const wrap = (text: string, font: typeof body, size: number): string[] => {
    const lines: string[] = []
    let line = ''
    for (const word of text.split(/\s+/)) {
      const next = line ? `${line} ${word}` : word
      if (font.widthOfTextAtSize(next, size) > width && line) {
        lines.push(line)
        line = word
      } else {
        line = next
      }
    }
    if (line) lines.push(line)
    return lines
  }

  const draw = (
    text: string,
    { font = body, size = 10.5, gap = 4, color = rgb(0.1, 0.1, 0.12) } = {}
  ): void => {
    for (const line of wrap(text, font, size)) {
      if (y < M + size) {
        page = doc.addPage([W, H])
        y = H - M
      }
      page.drawText(line, { x: M, y, size, font, color })
      y -= size * 1.35
    }
    y -= gap
  }

  draw(paper.patch.title ?? '', { font: bold, size: 16, gap: 10 })
  draw((paper.patch.authors ?? []).join(' · '), { font: italic, size: 11, gap: 2 })
  draw(AFFILIATION, { font: italic, size: 9, gap: 14, color: rgb(0.45, 0.45, 0.5) })
  draw(
    `${paper.patch.journal}, ${paper.patch.year}, ${paper.patch.volume}(${paper.patch.issue}), ${paper.patch.pages}`,
    { font: italic, size: 9.5, gap: 16, color: rgb(0.35, 0.35, 0.4) }
  )
  draw('Abstract', { font: bold, size: 11, gap: 4 })
  draw(paper.patch.abstract ?? '', { size: 10, gap: 18 })

  for (const section of paper.sections) {
    draw(section.heading, { font: bold, size: 12, gap: 5 })
    for (const p of section.paragraphs) draw(p, { gap: 9 })
    y -= 4
  }

  await fs.writeFile(path, await doc.save())
}

/**
 * Build a self-contained example library at `root`. Safe to point at an existing
 * folder: every step underneath is additive, so re-running tops it up rather
 * than destroying work.
 */
export async function createDemoLibrary(root: string): Promise<{ root: string; projectPath: string }> {
  await fs.mkdir(root, { recursive: true })

  // The PDFs are written to a scratch folder and imported through the real
  // importer, so they land in `sources/` under whatever naming and registry
  // rules the app currently applies.
  const staging = await fs.mkdtemp(join(tmpdir(), 'lectern-demo-'))
  try {
    const paths: string[] = []
    for (const paper of PAPERS) {
      const path = join(staging, paper.file)
      await writePdf(path, paper)
      paths.push(path)
    }

    const added = await addLibraryPapers(root, paths)
    for (let i = 0; i < PAPERS.length; i++) {
      const entry = added[i]
      if (!entry) continue
      // Fill in the metadata a real import would have got from Crossref or the
      // PDF itself...
      await updateLibraryPaper(root, entry.id, PAPERS[i].patch)
      // ...then let the app name the file, rather than trusting the name I
      // guessed above. Otherwise the first person to open the example would
      // watch all three PDFs rename themselves, which looks like a bug.
      await renamePaperToHouseStyle(root, entry.id)
    }

    const created = await createProject(
      root,
      'carbon-disclosure-review',
      {
        title: 'Does mandatory carbon disclosure inform investors?',
        authors: ['Your Name'],
        manuscriptFile: 'manuscript.qmd'
      },
      new Date().toISOString()
    )
    if (!created.ok || !created.projectPath) {
      throw new Error(created.error || 'could not scaffold the demo project')
    }

    // Foreground the two papers the manuscript actually cites; the third stays
    // in the pile, which is the normal state of a library.
    for (const citekey of ['ingram2024', 'vasquez2023']) {
      const paper = added.find((_, i) => PAPERS[i].patch.citekey === citekey)
      if (paper) await addProjectPaper(root, created.projectPath, paper.id)
    }

    await saveDoc(created.projectPath, MANUSCRIPT)
    return { root, projectPath: created.projectPath }
  } finally {
    await fs.rm(staging, { recursive: true, force: true }).catch(() => {})
  }
}
